#!/usr/bin/env bash

echo -e "Removing old builds..."
rm dist/Chromora.zip
rm dist/Chromora-light.zip

echo -e "Packing new builds..."
cd src
cp ../LICENSE LICENSE
zip -r ../dist/Chromora.zip assets classes data modules index.html style.css app.js manifest.json serviceWorker.js LICENSE
zip -r ../dist/Chromora-light.zip assets classes data modules index.html style.css app.js LICENSE
rm LICENSE
cd ..

echo -e "Done!"